import {THAI_SPECIAL_ASTROLOGY_CRITERIA,THAI_SPECIAL_CRITERIA_DECISIONS,THAI_SPECIAL_NAME_MERGE_DECISIONS,THAI_SPECIAL_CRITERIA_VERSION,getThaiSpecialCriteriaSummary} from '../data/thai-special-criteria.js';
import {PLANETARY_RELATIONS_VERSION,SIGN_RELATION_RULES,SPECIAL_RELATION_RULES} from '../data/planetary-relations.js';
import {DIGNITY_DATA_VERSION,ZODIAC_SIGNS,PLANETARY_DIGNITY_DATA,ADDITIONAL_DIGNITY_RULES} from '../data/planetary-dignities.js';

const root=document.getElementById('knowledgeApp');
if(root) renderKnowledge(root);

function renderKnowledge(root){
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const labels={id:'รหัส',name:'ชื่อ',aliases:'ชื่อเรียกอื่น',category:'หมวด',status:'สถานะข้อมูล',execution:'สถานะการใช้งาน',description:'คำอธิบาย',notes:'หมายเหตุ',planets:'ดาวที่เกี่ยวข้อง',requiredSigns:'ราศีที่กำหนด',housesFromAscendant:'ภพจากลัคนา',countedHousesFromAscendant:'ภพที่นับจากลัคนา',offsetsFromAscendant:'ระยะนับจากลัคนา',conditions:'เงื่อนไข',planetConditions:'เงื่อนไขดาว',requiredOccupancy:'เงื่อนไขการมีดาว',acceptedOccupants:'สิ่งที่นับเป็นผู้ครองตำแหน่ง',variants:'รูปแบบ/สำนัก',sources:'แหล่งอ้างอิง',evidence:'หลักฐาน',caveat:'ข้อควรระวัง',mergedInto:'รวมชื่อไว้กับรายการ',runtimeEnabled:'เปิดใช้ใน runtime',domicileSigns:'ราศีเกษตร',exaltation:'อุจจ์',debilitation:'นิจ',moolatrikona:'มูลตรีโกณ',dignityPolicy:'นโยบายมาตรฐานดาว',system:'ระบบอ้างอิง',countedSigns:'ลำดับราศีที่นับ',clockwiseOffsets:'ระยะนับตามจักร',approximateDegrees:'มุมโดยประมาณ',targetDegrees:'องศาเป้าหมาย',scope:'ขอบเขต',enabledForReference:'ใช้เป็นข้อมูลอ้างอิง',requiredToEnable:'สิ่งที่ต้องยืนยันก่อนเปิดใช้',state:'สถานะมติ',selectedVariant:'รูปแบบที่เลือก',selectedRule:'ข้อสรุปที่เลือก',unresolved:'ประเด็นที่ยังไม่ยืนยัน',criterionId:'รหัสเกณฑ์',ruleType:'ประเภทเกณฑ์',advisorDecision:'มติที่บันทึก',detail:'รายละเอียด',formula:'สูตร',planetNumber:'เลขดาว',element:'ธาตุ',english:'ภาษาอังกฤษ',index:'ลำดับ',degreeInSign:'องศาในราศี',fromDegree:'องศาเริ่ม',toDegreeExclusive:'องศาสิ้นสุด (ไม่รวม)',sign:'ราศี'};
 const key=k=>labels[k]||k.replace(/([a-z])([A-Z])/g,'$1 $2');
 function val(v,k=''){
  if(v==null||v==='')return '<span class="kp-muted">ยังไม่มีข้อมูล</span>';
  if(typeof v==='boolean')return v?'ใช่':'ไม่ใช่';
  if(Array.isArray(v))return v.length?'<ul>'+v.map(x=>'<li>'+val(x,k)+'</li>').join('')+'</ul>':'<span class="kp-muted">ไม่มีรายการ</span>';
  if(typeof v==='object')return '<dl class="kp-dl">'+Object.entries(v).map(([a,b])=>'<div><dt>'+esc(key(a))+'</dt><dd>'+val(b,a)+'</dd></div>').join('')+'</dl>';
  if(typeof v==='string'&&/^https?:\/\//i.test(v))return '<a href="'+esc(v)+'" target="_blank" rel="noopener noreferrer">'+esc(v)+'</a>';
  return esc(v);
 }
 const status=s=>({REFERENCE_ONLY:'อ้างอิงเท่านั้น',REFERENCE_PROVISIONAL:'อ้างอิงชั่วคราว',DISCOVERY:'อยู่ระหว่างรวบรวม',NEEDS_SOURCE:'ต้องหาแหล่งยืนยัน',SOURCE_VARIANT:'มีหลายรูปแบบตามสำนัก',ENABLED:'เปิดใช้งาน',DISABLED:'ยังไม่เปิดใช้',RECORDED_NOT_ENABLED:'บันทึกมติแล้ว แต่ยังไม่เปิดใช้'}[s]||s||'ไม่ระบุสถานะ');
 const card=(title,subtitle,badge,obj,group,id='')=>'<article class="kp-card" data-group="'+group+'" data-search="'+esc((title+' '+subtitle+' '+badge+' '+JSON.stringify(obj)).toLowerCase())+'" id="'+esc(id)+'"><header><div><h4>'+esc(title)+'</h4><small>'+esc(subtitle)+'</small></div><span>'+esc(badge)+'</span></header>'+val(obj)+'</article>';
 const signs=ZODIAC_SIGNS.map(s=>{
  const planets=Object.entries(PLANETARY_DIGNITY_DATA).filter(([,p])=>(p.domicileSigns||[]).includes(s.name)||p.exaltation?.sign===s.name||p.debilitation?.sign===s.name||p.moolatrikona?.sign===s.name).map(([planet,p])=>({planet,เกษตร:(p.domicileSigns||[]).includes(s.name),อุจจ์:p.exaltation?.sign===s.name?p.exaltation:null,นิจ:p.debilitation?.sign===s.name?p.debilitation:null,มูลตรีโกณ:p.moolatrikona?.sign===s.name?p.moolatrikona:null}));
  return card((s.index+1)+'. '+s.name+' ('+s.english+')','ราศีลำดับ '+s.index,'ธาตุ'+s.element,{...s,ดาวและมาตรฐานที่ระบุราศีนี้:planets},'signs');
 }).join('');
 const dignity=Object.entries(PLANETARY_DIGNITY_DATA).map(([n,v])=>card(n+(v.planetNumber?' · ดาว '+v.planetNumber:''),'มาตรฐานดาว',status(v.dignityPolicy),v,'dignities')).join('')+Object.entries(ADDITIONAL_DIGNITY_RULES).map(([n,v])=>card(n,'มาตรฐานเพิ่มเติม',v.runtimeEnabled?'เปิดใช้':'ยังไม่เปิดใช้',v,'dignities')).join('');
 const relations=Object.entries(SIGN_RELATION_RULES).map(([n,v])=>card(n,'เกณฑ์สัมพันธ์',v.scope||'reference',v,'relations')).join('')+Object.entries(SPECIAL_RELATION_RULES).map(([n,v])=>card(n,'รูปดวง/เกณฑ์พิเศษ',v.status||'reference',v,'relations')).join('');
 const criteria=THAI_SPECIAL_ASTROLOGY_CRITERIA.map(v=>card(v.name||v.id,v.id,status(v.execution||v.status),v,'criteria','kp-'+String(v.id||'').replace(/[^a-zA-Z0-9_-]/g,'-'))).join('');
 const decisions=[...THAI_SPECIAL_CRITERIA_DECISIONS.map(v=>({...v,kind:'มติเลือกสูตร'})),...THAI_SPECIAL_NAME_MERGE_DECISIONS.map(v=>({...v,kind:'มติรวมชื่อ/alias'}))].map((v,i)=>card(v.criterionId||v.name||v.id||v.kind,v.id||v.kind,status(v.state||v.status),v,'decisions','kp-decision-'+i)).join('');
 const summary=getThaiSpecialCriteriaSummary();
 root.innerHTML='<style>#knowledgeApp{min-width:0}.kp-intro{padding:13px 15px;background:#f6f8fe;border:1px solid #dce3f0;border-radius:12px;margin:12px 0}.kp-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px;margin:14px 0}.kp-stat{border:1px solid var(--line);border-radius:12px;padding:12px}.kp-stat b{display:block;font-size:22px;color:var(--navy)}.kp-stat span{font-size:12px;color:var(--muted)}.kp-tools{display:grid;grid-template-columns:2fr 1fr;gap:9px;margin:14px 0}.kp-tools input,.kp-tools select{width:100%;min-height:43px;border:1px solid #d7deeb;border-radius:10px;padding:9px 11px;font:inherit}.kp-tabs{display:flex;flex-wrap:wrap;gap:7px;margin:12px 0}.kp-tabs button{border:1px solid #d6deec;border-radius:999px;background:white;padding:8px 11px;font:inherit;font-size:12px;cursor:pointer}.kp-tabs button.active{background:var(--navy);color:white}.kp-group{margin:22px 0}.kp-group h3{color:var(--navy);font-size:17px}.kp-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.kp-card{border:1px solid var(--line);border-radius:12px;padding:13px;min-width:0;overflow-wrap:anywhere}.kp-card[hidden],.kp-group[hidden]{display:none!important}.kp-card header{display:flex;justify-content:space-between;align-items:flex-start;gap:8px;margin-bottom:8px}.kp-card h4{font-size:14px;margin:0;color:var(--navy)}.kp-card small{font-size:11px;color:var(--muted)}.kp-card header span{font-size:10px;padding:4px 7px;background:#f3f5fa;border:1px solid #e1e5ee;border-radius:999px;flex-shrink:0}.kp-dl{margin:0}.kp-dl>div{display:grid;grid-template-columns:minmax(90px,.7fr) minmax(0,1.4fr);gap:8px;border-top:1px solid #edf0f6;padding:7px 0}.kp-dl dt{font-size:12px;font-weight:700;color:#68758d}.kp-dl dd{font-size:12px;line-height:1.5;margin:0}.kp-dl ul{margin:0;padding-left:19px}.kp-muted{color:#9aa4b5;font-style:italic}#kpEmpty{display:none;text-align:center;padding:15px;color:var(--muted)}@media(max-width:700px){.kp-grid{grid-template-columns:1fr}.kp-stats{grid-template-columns:repeat(2,minmax(0,1fr))}.kp-tools{grid-template-columns:1fr}.kp-dl>div{grid-template-columns:minmax(85px,.65fr) minmax(0,1.35fr)}}</style>'+
 '<div class="kp-intro"><b>ขอบเขตข้อมูล:</b> รวบรวมความรู้จากคลังข้อมูลที่แยกอยู่ในโปรเจกต์ ไม่แก้สูตรคำนวณหลัก เกณฑ์อ้างอิงหรือยังไม่มีแหล่งยืนยันจะไม่ถูกเปิดใช้โดยอัตโนมัติ การรวมชื่อ/alias ไม่ได้แปลว่าสูตรต่างสำนักเหมือนกัน</div>'+
 '<div class="kp-stats"><div class="kp-stat"><b>'+ZODIAC_SIGNS.length+'</b><span>ราศี</span></div><div class="kp-stat"><b>'+Object.keys(PLANETARY_DIGNITY_DATA).length+'</b><span>ระเบียนมาตรฐานดาว</span></div><div class="kp-stat"><b>'+(Object.keys(SIGN_RELATION_RULES).length+Object.keys(SPECIAL_RELATION_RULES).length)+'</b><span>เกณฑ์สัมพันธ์/รูปดวง</span></div><div class="kp-stat"><b>'+summary.total+'</b><span>ระเบียนเกณฑ์พิเศษ · เปิดใช้ '+summary.executable+'</span></div></div>'+
 '<div class="kp-tools"><input id="kpSearch" type="search" placeholder="ค้นหาดาว ราศี เกณฑ์ คำอธิบาย หรือสถานะ…"><select id="kpSelect"><option value="all">ทุกหมวด</option><option value="signs">12 ราศี</option><option value="dignities">มาตรฐานดาว</option><option value="relations">เกณฑ์สัมพันธ์</option><option value="criteria">เกณฑ์พิเศษ</option><option value="decisions">มติ/ชื่อเรียก</option></select></div>'+
 '<div class="kp-tabs">'+[['all','ทั้งหมด'],['signs','12 ราศี'],['dignities','มาตรฐานดาว'],['relations','เกณฑ์สัมพันธ์'],['criteria','เกณฑ์พิเศษ'],['decisions','มติ/ชื่อเรียก']].map(([v,t])=>'<button data-tab="'+v+'" class="'+(v==='all'?'active':'')+'">'+t+'</button>').join('')+'</div><p id="kpCount" class="kp-muted"></p><div id="kpEmpty">ไม่พบข้อมูลที่ตรงกับคำค้น</div>'+
 '<section class="kp-group" data-section="signs"><h3>1. ราศีทั้ง 12</h3><div class="kp-grid">'+signs+'</div></section>'+
 '<section class="kp-group" data-section="dignities"><h3>2. มาตรฐานดาวและเกณฑ์เพิ่มเติม</h3><div class="kp-grid">'+dignity+'</div></section>'+
 '<section class="kp-group" data-section="relations"><h3>3. เกณฑ์สัมพันธ์และรูปดวงพิเศษ</h3><div class="kp-grid">'+relations+'</div></section>'+
 '<section class="kp-group" data-section="criteria"><h3>4. คลังเกณฑ์พิเศษทั้งหมด</h3><div class="kp-grid">'+criteria+'</div></section>'+
 '<section class="kp-group" data-section="decisions"><h3>5. มติที่บันทึกและการรวมชื่อ</h3><div class="kp-grid">'+decisions+'</div></section>'+
 '<div class="kp-intro"><b>เวอร์ชันข้อมูล:</b> เกณฑ์พิเศษ '+esc(THAI_SPECIAL_CRITERIA_VERSION)+' · เกณฑ์สัมพันธ์ '+esc(PLANETARY_RELATIONS_VERSION)+' · มาตรฐานดาว '+esc(DIGNITY_DATA_VERSION)+'. ข้อมูลที่ยังขาดสูตร/แหล่งอ้างอิงยังแสดงให้ตรวจสอบได้ แต่ไม่ถือเป็นสูตรใช้งานจริง</div>';
 let active='all';const input=root.querySelector('#kpSearch'),select=root.querySelector('#kpSelect'),count=root.querySelector('#kpCount'),empty=root.querySelector('#kpEmpty'),tabs=[...root.querySelectorAll('[data-tab]')];
 function apply(){const q=input.value.trim().toLowerCase(),chosen=select.value==='all'?active:select.value;let n=0;root.querySelectorAll('[data-section]').forEach(s=>{const sectionOn=chosen==='all'||s.dataset.section===chosen;s.hidden=!sectionOn;s.querySelectorAll('.kp-card').forEach(c=>{const show=sectionOn&&(!q||c.dataset.search.includes(q));c.hidden=!show;if(show)n++;});});count.textContent='แสดง '+n+' รายการ'+(q?' · คำค้น '+input.value:'');empty.style.display=n?'none':'block';tabs.forEach(t=>t.classList.toggle('active',select.value==='all'&&t.dataset.tab===active));}
 input.addEventListener('input',apply);select.addEventListener('change',()=>{active=select.value;apply();});tabs.forEach(t=>t.addEventListener('click',()=>{active=t.dataset.tab;select.value='all';apply();}));apply();
}
